---
title: "Compute Mann-Kendall Theil Sen of Precipitation"
author: "AJ Perez-Luque (@ajpelu); FJ Bonet; J Herrero and R. Perez-Perez and "
date: "2016 Jaunary"
output:  
    md_document:
      variant: markdown_github
---

```{r metadata, echo=FALSE}
########################################################
# Title: Compute Mann-Kendall Theil Sen of snow cover
# Date: Feb 2015
# version: v1
# Authors: Perez-Luque AJ (@ajpelu); Perez-Perez R and Bonet FJ 
################################################################

################################################################
# Set working directory 
machine <- 'ajpelu'
# machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/ownCloud/MS/CONGRESO_EGU2016/sn_snow_egu_2016', sep='')
################################################################
```

En primer lugar leemos los datos
```{r packages, warning=FALSE}
################################################################
# Load packages 
library('wq')
library('reshape2')
################################################################

################################################################
# Read data
raw_pre <- read.csv(file=paste(di, '/data/PXpxXyear.csv', sep=''), header=T, sep=',')

# Remove NaN
prec <- raw_pre[which(!is.na(raw_pre$pre)),]

# Rename 
names(prec) <- c('nie_malla_modi_id', 'pre', 'year')
                
################################################################
```

A continuación computamos la tendencia y la pendiente. Aplicamos la técnica de Mann-Kendall-Theil-Sen. El bucle realiza las siguientes operaciones: 

```{r}

# Prepare data. Transpose 
aux <- dcast(prec, year ~ nie_malla_modi_id, value.var = 'pre') 

# Create a zoo object 
auxts <- zoo(aux[-1],aux[,1])
  
# Compute Mann Kendall and Theil 
theil <- mannKen(as.ts(auxts))
  
# Prepare data output
theil <- as.data.frame(theil)
theil$nie_malla_modi_id <- rownames(theil)
  
# Round the output
theil$sen.slope <- round(theil$sen.slope, 3)
theil$sen.slope.pct <- round(theil$sen.slope.pct,2)
theil$p.value <- round(theil$p.value, 5)
theil$varS <- round(theil$varS, 2)
theil$tau <- round(theil$tau, 3)
################################################################
```
