---
title: "Maps of trends"
author: "AJ Perez-Luque (@ajpelu); FJ Bonet; J Herrero and R. Perez-Perez"
date: "2016 March"
output:  
    md_document:
      variant: markdown_github
---

```{r metadata, echo=FALSE}
################################################################
# Set working directory 

# machine <- 'ajpelu'
machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/MS/CONGRESO_EGU2016/sn_snow_egu_2016', sep='')
################################################################
```

```{r packages, warning=FALSE}
################################################################
# Load packages 
library("rgdal")
library("sp")
library("raster")
library("rasterVis") 
library("dplyr")
source(paste0(di,"/R/exportpdf.R")) # function to export raster levelplots maps as pdf

# Tool https://geoscripting-wur.github.io/ 
################################################################
```

## Prepare data

* Read topographic data and position (spatial) data
* Read snow cover trend data 
* 

```{r}
################################################################
# Read data

## Topographic data --- 
rawtopo <- read.csv(file=paste(di, "/data/topo_nie_malla_modis.csv", sep=""),
                    header=TRUE,
                    sep = ",") 

scd <- read.csv(file=paste(di, "/data/derived/scd.csv", sep= ""),
              header = TRUE,
              sep = ',')

topo <- rawtopo %>% 
  filter(id %in% scd$nie_malla_modi_id) %>% 
  mutate(nie_malla_modi_id = id) %>% 
  dplyr::select(nie_malla_modi_id, dem50mean) 
## ---  

## Trends data --- 
# Define name of indicators (see variables names)
indicadores <- c("scd", "scod", "scmd", "scmc", 
                 "pre", "pre_snow", "pre_snow_per", "temp",
                 "preau", "presp", "presu", "prewi",
                 "pnau", "pnsp", "pnsu", "pnwi",
                 "tempau", "tempsp", "tempsu", "tempwi")

# Loop to read files 
for (j in indicadores){ 
  aux <- read.csv(file=paste(di, "/data/derived/", j, ".csv", sep= ""),
              header = TRUE,
              sep = ',')
  aux <- aux %>%
    inner_join(topo, by='nie_malla_modi_id') 
  
  assign(j, aux)
}
## --- 



## Spatial Data --- 
# Read spatial data and Get lat/long
centroides <- rgdal::readOGR(dsn=paste(di, "/data/geoinfo", sep=""),
                             layer = "centroides_selected", verbose = FALSE)
# Select only attributes of interest and rename them
centroides <- centroides[c("id")]
names(centroides) <-"nie_malla_modi_id"

# Reproject to utm and m
centroides <- spTransform(centroides, CRS("+init=epsg:23030"))

# Get projection 
projection(centroides) 

# Which pixels are in the MKTrends objet
pix_comunes <- match(scd$nie_malla_modi_id, centroides$nie_malla_modi_id)

# Create spatial objetc with centroid of Sierra Nevada
centroides_sn <- centroides[pix_comunes,]
```


### Compute raster maps (all elevation) 

```{r}
# Loop to create raster map 
for (i in indicadores) { 
  trend <- get(i)
  
  # merge MKT and spatial pixel 
  aux_spatial <- sp::merge(x=centroides_sn, y=trend, by="nie_malla_modi_id")
  
  # raster auxiliar 
  aux_rast <- raster(aux_spatial, resolution=500)
  
  # variable z
  ztau <- paste("tau_",i, sep="")
  zsen <- paste("sen_slope_", i, sep="")
  
  # raster_tau 
  tau_raster <- rasterize(aux_spatial, aux_rast, ztau, fun=mean)
  names(tau_raster) <- i 
  sen_raster <- rasterize(aux_spatial, aux_rast, zsen, fun=mean)
  names(sen_raster) <- i 
  
  # assign 
  name_tau <- paste("r_tau_",i, sep="")
  name_sen <- paste("r_sen_",i, sep="")
  
  assign(name_tau, tau_raster)
  writeRaster(tau_raster, file=paste(di, "/data/derived/r_tau_", i, ".asc", sep=""), overwrite=TRUE)
  
  
  assign(name_sen, sen_raster)
  writeRaster(sen_raster, file=paste(di, "/data/derived/r_sen_", i, ".asc", sep=""), overwrite=TRUE)
  }


# Create stack of raster and save them 
# Tau stack 
stack_tau <- stack(r_tau_pre, r_tau_pre_snow, r_tau_pre_snow_per, r_tau_temp, 
                   r_tau_scd, r_tau_scod, r_tau_scmd, r_tau_scmc,
                   r_tau_preau, r_tau_presp, r_tau_presu, r_tau_prewi,
                   r_tau_pnau, r_tau_pnsp, r_tau_pnsu, r_tau_pnwi,
                   r_tau_tempau, r_tau_tempsp, r_tau_tempsu, r_tau_tempwi) 
                   

# Sen stack
stack_sen <- stack(r_sen_pre, r_sen_pre_snow, r_sen_pre_snow_per, r_sen_temp, 
                   r_sen_scd, r_sen_scod, r_sen_scmd, r_sen_scmc,
                   r_sen_preau, r_sen_presp, r_sen_presu, r_sen_prewi,
                   r_sen_pnau, r_sen_pnsp, r_sen_pnsu, r_sen_pnwi,
                   r_sen_tempau, r_sen_tempsp, r_sen_tempsu, r_sen_tempwi) 

# Export stacks
temp <- getwd()
setwd(paste(di, "/data/derived/", sep=""))
writeRaster(stack_tau, filename = 'r_tau_stack', overwrite =TRUE) 
writeRaster(stack_sen, filename = 'r_sen_stack', overwrite =TRUE) 
setwd(temp)
```


### Mask the stacks by elevation 

```{r}

# Create a raster of elevation mask 
aux_spatial_elev <- aux_spatial[c("nie_malla_modi_id", "dem50mean")]
elev_raster <- rasterize(aux_spatial_elev, aux_rast, "dem50mean", fun=mean)
elev_raster[elev_raster < 1250 ] <- NA

# Mask the stack 

stack_tau_1250 <- mask(stack_tau, elev_raster, updatevalue=NA)
stack_sen_1250 <- mask(stack_sen, elev_raster, updatevalue=NA)

# Save stacks 
temp <- getwd()
setwd(paste(di, "/data/derived/", sep=""))
writeRaster(stack_tau_1250, filename = 'r_tau_stack_1250', overwrite =TRUE) 
writeRaster(stack_sen_1250, filename = 'r_sen_stack_1250', overwrite =TRUE) 
setwd(temp)
```


```{r} 
# Auxiliar layer for Reproject the maps 
aux_project <- rgdal::readOGR(dsn=paste(di, "/data/geoinfo", sep=""),
                             layer = "centroides_selected", verbose = FALSE)

crs_aux_project <- projection(aux_project)

## Boundaries SN 
enp <- rgdal::readOGR(dsn=paste("/Users/", machine, "/Dropbox/carto_public/EENNPP/InfGeografica/InfVectorial/Shapes/ED50_30", sep=""),
                      layer = "EENNPP", verbose = FALSE)
# Subset limits of SN                      
sn <- subset(enp, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Espacio Natural')

# Reproject limits
sn_re <- spTransform(sn, CRS(crs_aux_project))



# Reproject Raster stack
stack_tau_1250_re <- projectRaster(stack_tau_1250, crs=crs(aux_project))
stack_sen_1250_re <- projectRaster(stack_sen_1250, crs=crs(aux_project))
```


## Snow cover trends indicators  
```{r}
lp <- levelplot(stack_tau_1250_re, 
          layer=c("scd","scod","scmd"), 
          par.settings=RdBuTheme,
          pretty=TRUE,
          #contour=TRUE,  
          #at=seq(-1,1, by=.1),
          layout=c(1,3)) + layer(sp.polygons(sn_re))


print(lp)

exportpdf(mypdf=paste0(di, '/images/raster_maps/r_taus_snow.pdf'), lp) 
```


## Snow cover duration  
```{r}
lp <- levelplot(stack_sen_1250_re, 
          layer="scd", 
          par.settings=RdBuTheme, 
          margin=FALSE,
          contour=TRUE, at=seq(-6,3, by=1),
          pretty=TRUE) + layer(sp.polygons(sn_re))


print(lp)

exportpdf(mypdf=paste0(di, '/images/raster_maps/r_sen_scd_latlong_contour.pdf'), lp) 

lp <- levelplot(stack_sen_1250_re, 
          layer="scd", 
          par.settings=RdBuTheme, 
          margin=FALSE,
          pretty=TRUE) + layer(sp.polygons(sn_re))


print(lp)

exportpdf(mypdf=paste0(di, '/images/raster_maps/r_sen_scd_latlong.pdf'), lp) 
```



## Annual precipitation and snow precipitation  
```{r}
lp <- levelplot(stack_tau_1250_re, 
          layer=c("pre","pre_snow", "pre_snow_per"), 
          par.settings=RdBuTheme, 
          margin=FALSE,
          pretty=TRUE,
          layout=c(1,3)) + layer(sp.polygons(sn_re))


print(lp)

exportpdf(mypdf=paste0(di, '/images/raster_maps/r_tau_precipitations_latlong.pdf'), lp) 
```


## Seasonal precipitation   
```{r}
lp <- levelplot(stack_tau_1250_re, 
          layer=c("preau",  "prewi", "presp", "presu"), 
          par.settings=RdBuTheme, 
          margin=FALSE,
          pretty=TRUE,
          layout=c(2,2)) + layer(sp.polygons(sn_re))

print(lp)

exportpdf(mypdf=paste0(di, '/images/raster_maps/r_tau_pre_season_latlong.pdf'), lp) 
```


## Seasonal snow precipitation 
```{r}
lp <- levelplot(stack_tau_1250_re, 
          layer=c("pnau",  "pnwi", "pnsp", "pnsu"), 
          par.settings=RdBuTheme, 
          margin=FALSE,
          pretty=TRUE,
          layout=c(2,2)) + layer(sp.polygons(sn_re))

print(lp)

exportpdf(mypdf=paste0(di, '/images/raster_maps/r_tau_pn_season_latlong.pdf'), lp) 
```



## Seasonal temperature
```{r}
lp <- levelplot(stack_tau_1250_re, 
          layer=c("tempau",  "tempwi", "tempsp", "tempsu"), 
          par.settings=RdBuTheme, 
          margin=FALSE,
          pretty=TRUE,
          layout=c(2,2)) + layer(sp.polygons(sn_re))

print(lp)

exportpdf(mypdf=paste0(di, '/images/raster_maps/r_tau_temp_season_latlong.pdf'), lp) 
```

















```{r, eval=FALSE, echo=FALSE}
#### ------- 
# old part
# Por aqui CARPINTO






# Map raster
# See https://github.com/oscarperpinan/spacetime-vis/blob/master/raster.R 

## Hillshade 
# Read HillShade Andalusia 
hs <- raster(paste('/Users/', machine, '/Dropbox/carto_public/sombra/sombra_Andalusia.tif', sep=''))
projection(hs) <- "+proj=utm +ellps=WGS84"

# Crop hillshade 
# as.vector(extent(r_sen_pre))
# create an extent object 
my_extent <- c(442000, 542000, 4070000, 4130000)

# Crop hillshade 
hs_sn <- crop(hs, my_extent)

## Boundaries SN 
enp <- rgdal::readOGR(dsn=paste("/Users/", machine, "/Dropbox/carto_public/EENNPP/InfGeografica/InfVectorial/Shapes/ED50_30", sep=""),
                      layer = "EENNPP", verbose = FALSE)
# Subset limits of SN                      
sn <- subset(enp, NOMBRE == 'SIERRA NEVADA' & FIGURA == 'Espacio Natural')



levelplot(r_sen_pre, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Pre")

levelplot(r_sen_temp, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Temp")

levelplot(r_sen_pre_snow, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Pre snow")

levelplot(r_sen_pre_snow_per, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Pre snow")

levelplot(r_sen_scd, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Scd")

levelplot(r_sen_scod, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Scod")

levelplot(r_sen_scmd, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Scmd")

levelplot(r_sen_scmc, 
          par.settings=RdBuTheme, margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Sen slope Scmc")


levelplot(r_tau_pre, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Pre")

levelplot(r_tau_temp, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Temp")

levelplot(r_tau_pre_snow, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Pre snow")

levelplot(r_tau_pre_snow_per, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Pre snow")

levelplot(r_tau_scd, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Scd")

levelplot(r_tau_scod, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Scod")

levelplot(r_tau_scmd, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Scmd")

levelplot(r_tau_scmc, 
          margin=FALSE, colorkey=TRUE, 
          contour=TRUE, 
          main="Tau  Scmc")



levelplot(r_tau_pre, margin = list(FUN = 'median'), contour=TRUE, par.settings=RdBuTheme)

# Option 2 

# Define the colour of the hillshade and set the transparency (alpha)
hsTheme <- modifyList(GrTheme(), list(regions=list(alpha=0.35)))
levelplot(r_sen_pre, panel=panel.levelplot.raster,
          par.settings=PuOrTheme, margin=FALSE, colorkey=TRUE) +
  levelplot(hs_sn, par.settings=hsTheme, maxpixels=1e6) + 
  levelplot(r_sen_pre, panel=panel.levelplot.raster,
          par.settings=PuOrTheme, margin=FALSE, colorkey=TRUE)
  
# + layer(sp.lines(sn, lwd=0.5))




PuOrTheme(
  RdBuTheme(region=brewer.pal(9, 'RdBu'), ...)
BuRdTheme






xxx <- projectRaster(r_tau_pre, crs = "+proj=longlat")





levelplot(stack_tau)
levelplot(r_tau_pre, margin = list(FUN = 'median'), contour=TRUE, par.settings=RdBuTheme)


# Download DEM data and create hillshade 

old <- setwd(tempdir())
download.file('http://biogeo.ucdavis.edu/data/diva/msk_alt/ESP_msk_alt.zip', 'ESP_msk_alt.zip')
unzip('ESP_msk_alt.zip', exdir='.')
dem <- raster('ESP_msk_alt')
setwd(old)

# Read DEM from Andalusia
dem <- raster(paste('/Users/', machine, '/Dropbox/carto_public/mde/TP_ELEV.asc', sep=''))
projection(dem) <- "+proj=utm +ellps=WGS84"

slope <- terrain(dem, 'slope')
aspect <- terrain(dem, 'aspect')
hs <- hillShade(slope=slope, aspect=aspect, angle=20, direction=30)


# HillShade Andalusia 
hs <- raster(paste('/Users/', machine, '/Dropbox/carto_public/sombra/sombra_Andalusia.tif', sep=''))
projection(hs) <- "+proj=utm +ellps=WGS84"

```

