---
title: "Plot combining raw values and trend (snow cover indicators)"
author: "AJ Perez-Luque (@ajpelu); FJ Bonet; J Herrero and R. Perez-Perez"
date: "2016 March"
output:
  md_document:
      variant: markdown_github
---

```{r metadata, echo=FALSE}
# Set working directory 

# machine <- 'ajpelu'
machine <- 'ajpeluLap'
di <- paste('/Users/', machine, '/Dropbox/MS/CONGRESO_EGU2016/sn_snow_egu_2016', sep='')
```

```{r packages, warning=FALSE, message=FALSE}
# Load packages 
library("raster")
library("rgdal")
library("sp")
library("dplyr")
library("ggplot2")
```

```{r, code=readLines(paste(di,'/R/autocaption.R', sep='')), echo=FALSE}
```


## Prepare Data

```{r}
# Read data (snow cover)
snow <- read.csv(file=paste(di, "/data/raw/snow_sn.csv", sep= ""), header = TRUE) 
# --   

# Read spatial data and Get lat/long
centroides <- rgdal::readOGR(dsn=paste(di, "/data/geoinfo", sep=""),
                             layer = "centroides_selected", verbose = FALSE)
# Select only attributes of interest and rename them
centroides <- centroides[c("id")]

# Create lat/lng by id 
xycentroides <- cbind(centroides@data, coordinates(centroides))
names(xycentroides) <- c("nie_malla_modi_id", "lon","lat")

xycentroides <- filter(xycentroides, nie_malla_modi_id %in% snow$nie_malla_modi_id)

# -- 

# Read Topographic data 
rawtopo <- read.csv(file=paste(di, "/data/topo_nie_malla_modis.csv", sep=""),
                    header=TRUE,
                    sep = ",") 
# function to convert radian to degree 
rad2deg <- function(rad) {(rad * 180) / (pi)} 


topo <- rawtopo %>% 
  filter(id %in% snow$nie_malla_modi_id) %>% 
  mutate(nie_malla_modi_id = id, 
         slope50mean_deg = rad2deg(slope50mean),
         slope50median_deg = rad2deg(slope50median),
         aspect50mean_deg = rad2deg(aspect50mean),
         aspect50median_deg = rad2deg(aspect50median)) %>%
  dplyr::select(nie_malla_modi_id, dem50mean, dem50median, slope50mean_deg, 
                slope50median_deg, aspect50mean_deg, aspect50median_deg) 
# -- 

## Hydrological basin 
basin <- read.csv(file=paste(di, "/data/derived/pixel_region.csv", sep=""),
                    header=TRUE,
                    sep = ",") 
# --


# Create objects with basis statistics for all indicators 
indicadores <- c("scd", "scod", "scmd", "scmc") 

# Loop to create objects with basis stats
for (i in indicadores) { 
  vnames <- c("nie_malla_modi_id", i) 
  aux <- snow %>%
    dplyr::select(one_of(vnames)) %>%
    mutate_(vinterest = i) %>%
    group_by_("nie_malla_modi_id") %>%
    summarise(mean=mean(vinterest),
              sd = sd(vinterest),
              cv = raster::cv(vinterest),
              se = sd / sqrt (length(vinterest))) %>%
    inner_join(topo, by="nie_malla_modi_id") %>%
    inner_join(xycentroides, by="nie_malla_modi_id") %>%
    inner_join(basin, by="nie_malla_modi_id")
  
  assign(i, aux)
} 

```

## Get mean values by basin 
```{r}
scd_basin <- scd %>% 
  filter(dem50mean > 1250) %>% 
  mutate(vinteres = mean) %>%
  group_by(basin_name) %>% 
  summarise(mean=mean(vinteres),
              sd = sd(vinteres),
              se = sd / sqrt (length(vinteres))) %>%
   mutate(variable = 'scd')

scod_basin <- scod %>% 
  filter(dem50mean > 1250) %>% 
  mutate(vinteres = mean) %>%
  group_by(basin_name) %>% 
  summarise(mean=mean(vinteres),
              sd = sd(vinteres),
              se = sd / sqrt (length(vinteres))) %>%
   mutate(variable = 'scod')
  
scmd_basin <- scmd %>% 
  filter(dem50mean > 1250) %>% 
  mutate(vinteres = mean) %>%
  group_by(basin_name) %>% 
  summarise(mean=mean(vinteres),
              sd = sd(vinteres),
              se = sd / sqrt (length(vinteres))) %>%
  mutate(variable = 'scmd')

```



# Trends
```{r}
stats_basin <- read.csv(file=paste(di, '/data/stats_basin.csv', sep=''), header=TRUE) 
```


```{r}
df_aux_scod <- stats_basin %>% 
  filter(variable == 'sen_slope_scod') %>%
  mutate(myxend = mean) %>% 
  select(basin_name, myxend) %>%
  inner_join(scod_basin, by='basin_name') 

# See exlore_snow_trends
df_aux_scod$letter <- c('c', 'c', 'a', 'c', 'b') 

df_aux_scmd <- stats_basin %>% 
  filter(variable == 'sen_slope_scmd') %>%
  mutate(myxend = mean) %>% 
  select(basin_name, myxend) %>%
  inner_join(scmd_basin, by='basin_name')

# See exlore_snow_trends  
df_aux_scmd$letter <- c('b', 'c', 'a', 'd', 'ab') 

df <- rbind(df_aux_scod, df_aux_scmd)


df_aux_scd <- stats_basin %>% 
  filter(variable == 'sen_slope_scd') %>%
  mutate(myxend = mean) %>% 
  select(basin_name, myxend) %>%
  inner_join(scd_basin, by='basin_name')
df_aux_scd$letter <- c('b','b','b','b','a')

```
 
```{r, echo=FALSE, fig.cap=fig$cap("trend_raw_all", "Mean values and trend for Snow cover indicators"), fig.height=6, fig.width=8}

g <- ggplot(df, aes(x=mean, y=basin_name)) + 
  geom_point(colour='black', size=4, fill='white', aes(shape=variable)) + 
  xlab('Day (hydrological year)') + ylab('') + 
  geom_segment(aes(x=mean, xend=mean+(10*myxend), y=basin_name, yend=basin_name, group=variable),
               arrow= arrow(length = unit(0.2, "cm"))) + 
  geom_text(aes(label=letter, x=mean, y=basin_name),
            hjust=0, nudge_y=0.3) + 
  geom_text(aes(label=round(myxend,2), x=mean+(5*myxend), y=basin_name),
            nudge_y=0.1) +
  theme_bw() + theme(panel.grid.major=element_blank(),
                       panel.grid.minor=element_blank(),
                       strip.background=element_rect(fill='white')) 
  

print(g)

ggsave(filename=paste0(di, '/images/trend_raw_all.pdf'), plot=g, height = 6, width = 8) 
dev.off()
```




```{r, echo=FALSE, fig.cap=fig$cap("trend_raw_scod", "Mean values and trend for Snow cover Onset date"), fig.height=6, fig.width=8}
g <- ggplot(df_aux_scod, aes(x=mean, y=basin_name)) + 
  ggtitle('Snow-cover onset date') +
  xlab('Day (hydrological year)') + ylab('') +  
  geom_segment(aes(x=mean, xend=mean+(2*myxend), y=basin_name, yend=basin_name, group=variable),
               arrow= arrow(length = unit(0.2, "cm"))) + 
  geom_point(colour='black', shape=21, size=4, aes(fill=letter)) +
  # geom_point(colour='black', shape=21, size=4, fill='white') +
  geom_text(aes(label=letter, x=mean, y=basin_name),
            hjust=0, nudge_y=0.3) + 
  geom_text(aes(label=round(myxend,2), x=mean+(2*myxend), y=basin_name),
            nudge_x=1) + 
  theme_bw() + theme(panel.grid.major=element_blank(),
                     panel.grid.minor=element_blank(),
                     strip.background=element_rect(fill='white'),
                     legend.position = "none")

print(g)

ggsave(filename=paste0(di, '/images/trend_raw_scod.pdf'), plot=g, height = 6, width = 8) 
dev.off()

```




```{r, echo=FALSE, fig.cap=fig$cap("trend_raw_scmd", "Mean values and trend for Snow cover melting  date"), fig.height=6, fig.width=8}
g <- ggplot(df_aux_scmd, aes(x=mean, y=basin_name)) + 
  ggtitle('Snow-cover melting date') +
  xlab('Day (hydrological year)') + ylab('') +  
  geom_segment(aes(x=mean, xend=mean+(2*myxend), y=basin_name, yend=basin_name, group=variable),
               arrow= arrow(length = unit(0.2, "cm"))) + 
  geom_point(colour='black', shape=21, size=4, aes(fill=letter)) +
  # geom_point(colour='black', shape=21, size=4, fill='white') +
  geom_text(aes(label=letter, x=mean, y=basin_name),
            hjust=0, nudge_y=0.3) + 
  geom_text(aes(label=round(myxend,2), x=mean+(2*myxend), y=basin_name),
            nudge_x=-2) + 
  theme_bw() + theme(panel.grid.major=element_blank(),
                     panel.grid.minor=element_blank(),
                     strip.background=element_rect(fill='white'),
                     legend.position = "none")
print(g)

ggsave(filename=paste0(di, '/images/trend_raw_scmd.pdf'), plot=g, height = 6, width = 8) 
dev.off()

```



```{r, echo=FALSE, fig.cap=fig$cap("trend_scd", "Mean values and trend for SCD"), fig.height=6, fig.width=8}

g <- ggplot(df_aux_scd, aes(y=mean, x=basin_name)) + 
  geom_bar(stat='identity', colour="black", fill="white", width = 0.8) + 
  coord_flip() + 
  geom_segment(aes(y=mean, yend=mean+(10*myxend), x=basin_name, xend=basin_name, colour=letter),
               arrow= arrow(length = unit(0.4, "cm"), type="closed"), size=1.7) + 
  geom_text(aes(label=letter, y=mean+(5*myxend), x=basin_name),
            hjust=0, nudge_x=-0.2) + 
  geom_text(aes(label=round(myxend,2), y=mean+(5*myxend), x=basin_name),
            nudge_x=0.2) +
  xlab('') + ylab('Snow cover duration (average, days)') +
  theme_bw() + theme(panel.grid.major=element_blank(),
                     panel.grid.minor=element_blank(),
                     strip.background=element_rect(fill='white'),
                     legend.position = "none") +
  scale_color_manual(values=c("#1F497D","#808080"))
  
  
print(g)

ggsave(filename=paste0(di, '/images/trend_raw_scd.pdf'), plot=g, height = 6, width = 8) 
dev.off()
```

